export const FETCH_MENU_CATEGORY_SUCCESS = {type:'FETCH_MENU_CATEGORY_SUCCESS'};
export const HANDLE_INPUT_CATEGORY_NAME = {type: 'HANDLE_INPUT_CATEGORY_NAME'};
export const HANDLE_INPUT_CATEGORY_ID = {type:'HANDLE_INPUT_CATEGORY_ID'};
export const EDIT_DATA = {type:'EDIT_DATA'};